### PR TITLE
Allow it to work under Xvfb.

### PR DESCRIPTION
**Pull request by notriddle**
Part of servo/servo#8641

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/63)

### CODE REVIEW

**Comment by emilio** [comment]
Is there a reason for this not going upstream to tomaka/glutin?

**Comment by emilio** [comment]
We've recently being able to update glutin again, so another glutin update from upstream shouldn't be a problem.

BTW, @notriddle, you were the first to report [the glutin crash on linux a few weeks ago](https://gist.github.com/notriddle/3c0dff9b4dc3a1a7b82f), can you confirm that's fixed?

**Comment by notriddle** [comment]
> Is there a reason for this not going upstream to tomaka/glutin?

Not really, no. I'll backport it.

**Comment by notriddle** [comment]
Backported as tomaka/glutin#710

**Comment by notriddle** [comment]
> BTW, @notriddle, you were the first to report the glutin crash on linux a few weeks ago, can you confirm that's fixed?

Confirmed.

**Pull request closed without merging**
