### PR TITLE
Port over robertknight's X11 scroll speed fix

### PR DESCRIPTION
**Pull request by pcwalton**
r? @mbrubeck

### CODE REVIEW

**Comment by pcwalton** [comment]
Looks like this repo isn't homu-ified. Shall I just use the green button? (@metajack?)

**Comment by pcwalton** [comment]
@metajack What happened here?

**Comment by metajack** [comment]
Merging by hand. I think the homu integration was in a partial state and the travis builds are failing for other reasons.

**Comment by SimonSapin** [comment]
Does homu support merging PRs into branches other than master?

**Comment by metajack** [comment]
@SimonSapin That is a good question. @barosl ?

**Comment by metajack** [comment]
Looks like we need master = "servo" in the cfg.toml for homu. I'll do a PR for that.

**Comment by metajack** [comment]
Submitted servo/saltfs#60

**Pull request merged**
