### PR TITLE
Glutin update

### PR DESCRIPTION
**Pull request by paulrouget**
Previous PR (#43) was against the master branch, not the servo branch.

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/44)

### CODE REVIEW

**Comment by paulrouget** [comment]
On Linux, we're getting this error:

```
[glutin] x error code=53 major=0 minor=0!
thread '<main>' panicked at 'Failed to compile shader: ', /home/gw/code/work/servo_alt/servo/.cargo/git/checkouts/rust-layers-c02709c0157e02cd/master/src/rendergl.rs:163
```

Shader compilation failing.

Using glx instead of egl fixes the issue.

We could make it possible to select glx instead of egl, or update the shaders used in servo, or maybe there's a way to configure egl to be less strict.

@tomaka, what would you recommend?

**Comment by glennw** [comment]
Unfortunately the shader compiler error log is empty for me - I'm trying out a few things to narrow down what's actually causing the shader compilation to fail.

**Comment by glennw** [comment]
Hmm, according to https://wiki.debian.org/ATIProprietary#AMD_Catalyst_14.9 (which might be out of date) fglrx (which is what this machine is running) doesn't support EGL. And enabling the mesa egl debug output, it does look like it's loading a software implementation of EGL on my machine.

**Comment by glennw** [comment]
@paulrouget Switching the lines in x11/window.rs to prefer GLX over EGL makes it work on my machine, and is probably a safe bet. Perhaps we could add our own local patch for that, and then do some further investigation as a follow up?

@metajack Although I don't really want to delay merging this, perhaps we should wait until after mid-week anyway, to avoid any android issues?

**Comment by paulrouget** [comment]
On my linux VM:

Glutin's window example, with servo/glutin/servo-2015-08-14. Screen is ok (green). No X error. Logs:
```
OpenGL version 2.1 Mesa 10.1.3
```

Servo + servo/glutin/servo-2015-08-14. Google.com renders properly.  Logs:
```
[glutin] x error code=50 major=0 minor=0!
```

Glutin's window example, with paulrouget/glutin/glutin-update. Screen is corrupted.
Same with tomaka's master.
Logs:
```
libEGL warning: DRI2: failed to authenticate
Pixel format of the window: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 32, stencil_bits: 0, stereoscopy: false, double_buffer: true, multisampling: None, srgb: false }
OpenGL version 2.1 Mesa 10.1.
Resized(798, 544)
Refresh
[glutin] x error code=54 major=0 minor=0!
[glutin] x error code=56 major=0 minor=0!
```

Glutin's window example, with paulrouget/glutin/glutin-update, using glx. Screen is ok (green).
Same with tomaka's master.
Logs:
```
[glutin] x error code=50 major=0 minor=0!
[glutin] x error code=53 major=0 minor=0!
Pixel format of the window: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 32, stencil_bits: 0, stereoscopy: false, double_buffer: true, multisampling: None, srgb: false }
OpenGL version 2.1 Mesa 10.1.3
```

Servo + paulrouget/glutin/glutin-update. Screen is corrupted. Logs:
```
libEGL warning: DRI2: failed to authenticate
[glutin] x error code=53 major=0 minor=0!
...
```

Servo + paulrouget/glutin/glutin-update, using glx. Crash:
```
[glutin] x error code=50 major=0 minor=0!
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', src/libcore/result.rs:732
```

Which is I guess: https://github.com/tomaka/glutin/issues/314

**Comment by tomaka** [comment]
I guess I'm going to revert to GLX by default instead of EGL.

**Comment by paulrouget** [comment]
> I guess I'm going to revert to GLX by default instead of EGL.

Want me to do a PR?

**Comment by tomaka** [comment]
> Want me to do a PR?

That would be nice :)

It's just a two lines fix, but I'm a bit lazy.

**Pull request merged**
