### PR TITLE
Glutin update

### PR DESCRIPTION
**Pull request by paulrouget**
Vlad's commits are not necessary anymore, and older commits have bitrotted. Instead of piling commits to correct these, I thought I'd just rebase the branch.

I might have broken the parent window features. Not sure how to test that.

`ports/glutin/Cargo.toml` in Servo will need an update too as glutin doesn't have a "window" feature anymore. I'll take care of that once we have the new branch glutin/servo branch.

This PR is against a clone of tomaka/glutin/master. Once this PR is approved, we'll update the servo branch.

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/51)

### CODE REVIEW

**Comment by paulrouget** [comment]
Not sure why there's a merge conflict.

Can someone merge this branch in master_20151021 and then update the servo branch?

**Comment by mbrubeck** [comment]
I copied the old `servo` branch to `servo-2015-10-23` and then force-pushed these commits to the `servo` branch.

**Pull request closed without merging**
