### PR TITLE
Fix handling of numpad keys w.r.t. numlock (derived from fix mentione…

### PR DESCRIPTION
**Pull request by aweinstock314**
…d at http://www.kaffe.org/pipermail/kaffe/2000-April/175201.html).

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/22)

### CODE REVIEW

**Comment by jdm** [comment]
This should go upstream to https://github.com/tomaka/glutin, I think.

**Comment by aweinstock314** [comment]
I have a local branch of tomaka/glutin that I've cherry-picked the commit onto, but servo doesn't compile with that version of glutin. I have tested this branch with servo, and verified that it allows numbers to be entered into textboxes with the numpad. Should I PR the branch of tomaka/glutin/master, then do a seperate PR rebasing servo/glutin/servo onto tomaka/glutin/master (once the former is accepted)?

**Comment by jdm** [comment]
I don't know what the current setup is; do you @larsbergstrom?

**Comment by metajack** [comment]
Generally for forks of community projects we should always land upstream, and then cherry pick down to our fork. When the next rust upgrade happens, we'll be back on upstream master hopefully.

We should probably be naming our fork branches servo-20YYMMDD so that this is clearer.

**Comment by larsbergstrom** [comment]
@metajack We should probably talk at the meeting about this. We've been having trouble with landing changes required for CEF into upstream glutin due to differing design goals upstream and may end up with a fork.

**Comment by aweinstock314** [comment]
https://github.com/tomaka/glutin/pull/456

**Comment by jdm** [comment]
This went upstream so we're covered.

**Pull request closed without merging**
