### PR TITLE
update/rebase onto latest glutin

### PR DESCRIPTION
**Pull request by zmike**
r? @glennw @pcwalton

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/36)

### CODE REVIEW

**Comment by zmike** [comment]
@larsbergstrom

**Comment by tomaka** [comment]
Link to diff between this branch and current glutin master: https://github.com/tomaka/glutin/compare/master...zmike:master

Looks good to me at least.

**Comment by glennw** [comment]
@zmike It seems to be missing the extra patch I added that requires Weak<>. This is needed to stop X11 crashes in some drivers due to how we use X11 from threads.

**Comment by zmike** [comment]
@glennw hm that must have gotten taken out of the rebase somehow. It's in now.

**Comment by zmike** [comment]
More updates.

**Comment by tomaka** [comment]
To give a summary of what has changed in upstream glutin that are relevant for Servo since the last rebase:

 - The whole crate has been reorganized. Individual APIs (for example EGL, GLX, X11, Wayland, OSMesa) each go in their own directory.
 - All libraries are now loaded at runtime with `dlopen` on Linux, so you don't even need to have these libraries installed in order to compile glutin (this is essential to support both wayland and X11, and is super useful when you cross-compile).
 - Support for wayland has been added but is disabled at runtime for the moment.
 - The mouse wheel events have changed in order to fix the fact that it's too slow.
 - `make_current` and `swap_buffers` return a `Result` in order to handle the `EGL_CONTEST_LOST` error.
 - Support for robustness has been added, which is something that browsers usually like. You can pass `with_gl_robustness(glutin::Robustness::TryRobustLoseContextOnReset)` at creation.

**Comment by zmike** [comment]
Should be okay now, though GH isn't updating so I can't tell for sure...

**Comment by zmike** [comment]
I'm pretty sure this is going to require a yolo force push since it rewrites history. I'll do a rebase on my rebased rebase to squash some of our commits and make the patchset smaller for future rebases.

**Comment by metajack** [comment]
@zmike force push away then.

**Comment by Ms2ger** [comment]
Let's not force push, that breaks building old versions of Servo. Just merge in the new commits.

**Comment by metajack** [comment]
Or push to a servo-date branch and switch to that branch in cargo tomls

**Comment by SimonSapin** [comment]
Let’s not change `Cargo.toml` files. Older Servo versions have `Cargo.lock` that contain commit hashes. As long as these commits are reachable from any branch (so that they’re not garbage-collected), things will work out.

**Comment by metajack** [comment]
So you want to push to a servo-$date branch but then continue to tell cargo it's the servo branch?

I think while that may work in the common case, what happens when someone manually pulls that branch and sets and override in order to work there? I think that would just be confusing.

**Comment by SimonSapin** [comment]
> So you want to push to a servo-$date branch but then continue to tell cargo it's the servo branch?

Yes. When building older Servo commits, Cargo will find the glutin commit based on the hash in `Cargo.lock`. It will only care about the branch in `Cargo.toml` if `cargo update` is run.

> I think while that may work in the common case, what happens when someone manually pulls that branch and sets and override in order to work there? I think that would just be confusing.

Servo master will be updated to the new glutin, right? So the `servo-$date` branches only matter when building older Servo commits. And if you need path overrides *and* older Servo, then you’d have to checkout your glutin clone at the relevant glutin commit anyway.

**Comment by zmike** [comment]
I've put up a rebased+squashed branch. Someone who knows cargo better than me can decide how/when/where to push it to and how to do build system updates for it.

**Comment by metajack** [comment]
@SimonSapin I think you misunderstood me. It was suggested we should not force push the servo branch. So we have to put this work on a new branch. But then we should update all the Cargo.tomls to point to the correct branch.

I think you are suggesting that push the current servo branch to servo-$date and then force push this PR to servo, in which case we wouldn't need to rename the branch in Cargo.toml and old commits will still work.

@zmike has said he has no more time for this really, so we should decide quickly which to do.

**Comment by farodin91** [comment]
Currently I'm working on the viewport issue https://github.com/servo/servo/pull/6875. That would helpful for my implementation.

**Comment by paulrouget** [comment]
> @zmike has said he has no more time for this really, so we should decide quickly which to do.

So what's happening now? Anyone is looking at this?

Is it just a matter of adding these 7 extra commits (https://github.com/tomaka/glutin/compare/master...zmike:master) to tomaka's master into a new servo/glutin branch?

**Comment by glennw** [comment]
The best way going forward is to port and upstream https://github.com/servo/glutin/pull/37, then take upstream master, apply zmike's parent changes as a patch. In theory that is the only change we should need from upstream now, but there may be a few that have happened since that haven't been upstreamed. I've been meaning to look into this but just haven't had time, sorry.

**Comment by paulrouget** [comment]
I'll give it a try.

**Comment by paulrouget** [comment]
https://github.com/servo/glutin/pull/43

**Comment by mbrubeck** [comment]
Superseded by #43

**Pull request closed without merging**
