### PR TITLE
cocoa: Don't report wakeups from other threads via the `WindowProxy` as real events.

### PR DESCRIPTION
**Pull request by pcwalton**
This improves scrolling performance in Servo a lot, because scrolling
events in the queue would back up behind wakeup events.

r? @glennw or @metajack

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/18)

### CODE REVIEW

**Comment by metajack** [comment]
Does this mean we should process more than one event per event loop turn?

**Comment by pcwalton** [comment]
Maybe. I think that should be done in a followup if at all. We don't want to process more than one scrolling event per event loop turn, at least for now I don't think. This at least restores the old behavior that we used to have.

**Comment by glennw** [comment]
@pcwalton Could you upstream this if it isn't already?

**Comment by waddlesplash** [comment]
It isn't upstreamed already.

**Comment by jdm** [comment]
Did this ever go upstream?

**Comment by metajack** [comment]
pinging @pcwalton

**Comment by jdm** [comment]
@pcwalton Did this ever make it upstream? Can we either do that or close this PR?

**Comment by glennw** [comment]
I'm assuming this can be closed - reopen if we still want to do something here.

**Pull request closed without merging**
