### PR TITLE
glutin fixes for win32

### PR DESCRIPTION
**Pull request by vvuk**
This PR fixes some dep versions (on user32-sys), stubs out some functions to avoid unimplemented!() panics, and fixes BuilderAttribs to not have a bare *c_void for which the Send trait does not exist.

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/48)

### CODE REVIEW

**Comment by mbrubeck** [comment]
I think this should go to upstream (tomaka/glutin) first, and then we'll merge it here.

**Comment by vvuk** [comment]
Upstream PR for the win32 stuff: https://github.com/tomaka/glutin/pull/611

**Comment by paulrouget** [comment]
This PR breaks compilation on Mac:

```
   Compiling glutin_app v0.0.1 (file:///Users/paul/git/servo/components/servo)
/Users/paul/git/servo/ports/glutin/window.rs:93:42: 93:48 error: mismatched types:
 expected `core::option::Option<glutin::WindowID>`,
    found `glutin::WindowID`
(expected enum `core::option::Option`,
    found struct `glutin::WindowID`) [E0308]
/Users/paul/git/servo/ports/glutin/window.rs:93                             .with_parent(parent)
                                                                                         ^~~~~~
/Users/paul/git/servo/ports/glutin/window.rs:93:42: 93:48 help: run `rustc --explain E0308` to see a detailed explanation
/Users/paul/git/servo/ports/glutin/window.rs:122:18: 122:47 error: mismatched types:
 expected `glutin::WindowID`,
    found `*mut libc::types::common::c95::c_void`
(expected struct `glutin::WindowID`,
    found *-ptr) [E0308]
/Users/paul/git/servo/ports/glutin/window.rs:122         unsafe { self.window.platform_window() }
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/git/servo/ports/glutin/window.rs:122:18: 122:47 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
```

**Comment by Ms2ger** [comment]
And Linux, but only if you update glutin.

**Comment by vvuk** [comment]
Mm, yes, those need some Some() action and a cast to WindowID.  This is all from getting rid of the bare c_void ptr usage.  I don't have a mac easily accessible; can someone do the quick fixes?

**Pull request merged**
