### PR TITLE
Fix compiler error about mutable transmutes

### PR DESCRIPTION
**Pull request by michaelwu**

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks like this change is already upstream. Can we just update?

**Comment by SimonSapin** [comment]
CC @glennw

**Comment by mbrubeck** [comment]
We've diverged from upstream, which lacks the "headless" feature, so I don't think we can just update.  We're hoping to merge back together at some point, but let's take this fix for now.

**Comment by mbrubeck** [comment]
> We've diverged from upstream, which lacks the "headless" feature

@glennw points out we haven't diverged so much as fallen behind. In any case, we can do the work to update soon.

**Pull request merged**
