### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by SimonSapin**
CC #56

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/57)

### CODE REVIEW

**Comment by adamncasey** [comment]
Is there a process to kick off a new crates.io version so this can be referenced in the servo build?

Thanks!

**Comment by larsbergstrom** [comment]
Anyone in  @servo/cargo-publish should be able to do so.

**Comment by SimonSapin** [comment]
There is no formal process other than asking someone who has access like you did here. On an issue tracker or on IRC. Everyone in @servo/cargo-publish should have access to publish any crate whose source is under github.com/servo, and it looks like they get notified if you mention that name on github.

I just published servo-glutin 0.4.5.

**Pull request merged**
