### PR TITLE
Remove wayland support and dependencies

### PR DESCRIPTION
**Pull request by mbrubeck**
Our glutin fork has diverged significantly from upstream, and it will take significant work to merge them, or to move to some new windowing API built on top of glutin, winit, or otherwise.

In the meantime we are building very old Wayland libraries but never using them (#108).  As a short-term patch to improve Servo build times by not building a bunch of unused dependencies, this patch just rips out the unused wayland support from our fork.  (This code is already gone from upstream glutin, moved into `winit` and using newer, rewritten wayland crates.)

r? @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/glutin/115)

### CODE REVIEW

**Comment by mbrubeck** [comment]
I'm not sure why GitHub is showing a Travis failure on this PR.  Travis itself shows success.

**Comment by jdm** [comment]
The OS X travis jobs were cancelled due to a massive OS X infrastructure problem at TravisCI.

**Comment by glennw** [comment]
r=me when the conflicts are resolved.

**Pull request merged**
