### PR TITLE
libc::c_void -> std::raw::os::c_void

### PR DESCRIPTION
**Pull request by adamncasey**
Fixes the build on windows.

May need careful style & cross-platform review, it's my first PR in rust & I don't have a good way to check this works on other platforms.

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/56)

### CODE REVIEW

**Comment by adamncasey** [comment]
Is it possible to configure the CI build for windows as well? This has likely been broken for some time

**Comment by SimonSapin** [comment]
It looks like the upstream repository already has a similar change: https://github.com/tomaka/glutin/commit/816fbb2165e3d2f5656a3afa9d9553551c0c6b68 (and they have CI for Windows.)

I’ll do a merge.

**Comment by adamncasey** [comment]
Oh nice, perfect

**Comment by SimonSapin** [comment]
By the way, unless they have a specific reason not to, PRs to this repo should probably go upstream instead.

**Pull request closed without merging**
