### PR TITLE
cocoa: Reuse a single thread-local `NSEvent` instance instead of repeatedly creating a new one when waking up the event loop from another thread.

### PR DESCRIPTION
**Pull request by pcwalton**
This also avoids sending this event to the `NSApplication`, since that's
needless overhead.

Reduces CPU usage of a simple `requestAnimationFrame()` loop in Servo by
23%.

Partially addresses servo/servo#9844.

r? @paulrouget

---

This change is [Reviewable](https://reviewable.io/reviews/servo/glutin/87)

### CODE REVIEW

**Comment by paulrouget** [comment]
Looks good to me, but can you explain why we were initially skipping NSKeyDown? And why do we now also skip NSApplicationDefined?

**Comment by pcwalton** [comment]
I assume we were skipping `NSKeyDown` because otherwise nothing will handle it and it'll beep. As for skipping `NSApplicationDefined`, it's a CPU usage optimization for servo/servo#9844. Nothing will handle it, so it's a waste of CPU to send it to the window.

**Comment by paulrouget** [comment]
Hmm, thought I did. Anyway. r+

**Pull request merged**
