### PR TITLE
x11: handle X11's multi-key, a.k.a compose key.

### PR DESCRIPTION
**Pull request by emilio**
r? @jdm

---

This change is [Reviewable](https://reviewable.io/reviews/servo/glutin/101)

### CODE REVIEW

**Comment by emilio** [comment]
I'm trying to upstream this change too: https://github.com/tomaka/glutin/pull/800

**Comment by jdm** [comment]
I guess it looks fine? I don't really know anything about how compose keys work.

**Comment by emilio** [comment]
Fair enough: r? @mbrubeck then maybe?

**Comment by emilio** [comment]
We could also wait for tomaka to review the upstream patch I guess.

**Comment by emilio** [comment]
This was r+ in https://github.com/tomaka/glutin/pull/800

@bors-servo: r=tomaka

**Pull request merged**
