### PR TITLE
Bump winapi to 0.3

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/glutin/140)

### CODE REVIEW

**Comment by Eijebong** [comment]
I can't test it. `cargo check` says there are no errors but I would appreciate if anyone could run tests and report if it works or not :)

**Comment by jdm** [comment]
I'm seeing if we can get appveyor enabled on this repository.

**Comment by Eijebong** [comment]
This one was forgotten :p

**Comment by jdm** [comment]
I have restarted the specific travis sub-job that timed out.

**Comment by atouchet** [comment]
@Eijebong did this ever get tested? Something presumably broke the Windows Servo build in the upgrade from 0.13.4 to 0.14.0 (see https://github.com/servo/servo/issues/19901).

**Comment by Eijebong** [comment]
@atouchet I never tested it but I think we talked about this already on IRC and nobody saw anything wrong with this PR

**Comment by atouchet** [comment]
@Eijebong I don't mean to be a pain but how feasible would it be to temporarily revert back to the previous version of winapi? This version appears to be breaking the Windows Servo build (https://github.com/servo/webrender/issues/2356) and it sounds like Servo won't be switching to upstream Glutin for a couple of weeks or more.

**Comment by jdm** [comment]
I would be willing to merge that PR.

**Comment by Eijebong** [comment]
@atouchet Sure, we haven't deduped winapi in servo because of mio anyway.

**Comment by atouchet** [comment]
Okay, what needs to be done in that case? Revert this commit and bump the Glutin version number? Would you be willing to open a PR as you have a better idea of what you're doing or would you rather that I do it?

**Comment by Eijebong** [comment]
I can't do it right now but yeah reverting + bumping the version number should be enough

**Comment by retep998** [comment]
What I'd really appreciate is someone figuring out what is actually at fault so the bug can be fixed instead of just blindly reverting.

**Comment by jdm** [comment]
Unfortunately we're short on developers with access to Windows development environments, and the Windows nightly has suffered enough.

**Pull request merged**
