### PR TITLE
update to image 0.16

### PR DESCRIPTION
**Pull request by tigercosmos**
update to image 0.16

r? @jdm

---
This change is [Reviewable](https://reviewable.io/reviews/servo/glutin/128)

### CODE REVIEW

**Comment by jdm** [comment]
Please increase the version number for this crate to 0.12.1, too.

**Comment by tigercosmos** [comment]
Sure.

**Comment by jdm** [comment]
Published.

**Comment by tigercosmos** [comment]
Thanks

**Pull request merged**
