### PR TITLE
add ability to set parent window when creating windows

### PR DESCRIPTION
**Pull request by zmike**
This is needed for use in Servo.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Should this go upstream as well?

**Comment by Manishearth** [comment]
cc @tomaka

**Comment by tomaka** [comment]
Hmm, that's borderline with the scope of glutin.

Glutin is supposed to create a window with an OpenGL context, and not become a complete GUI system like Qt.

**Comment by zmike** [comment]
I'm only adding things that are going to be directly used internally by Servo. Extending it to be a full toolkit is not something that I have any interest in.

**Comment by Manishearth** [comment]
We should avoid diverging from the regular community crates as much as possible -- perhaps this can be solved by providing a generic pluggable API in glutin to do stuff like this? (I'm not sure what's being done here so I don't know if that is the right solution)

**Comment by tomaka** [comment]
The problem is that each feature added to glutin is something that I must maintain and propagate to other platforms as well.

For example the `WindowProxy`, the ability to set the current cursor (I don't remember if that's used by servo or not), or the `platform_display`/`platform_window` functions are unimplemented on win32 and android. Requesting the latest OpenGL version on X11 doesn't work. Just a week ago, the depth buffer size/color bits/etc. were simply ignored on Android.

According to a quick github search, there are 12 functions that contain just `unimplemented!()` in glutin's source code. And that's not even counting the creation parameters that are simply ignored. If you add the ability to set the parent window, it will add yet another thing that is not implemented everywhere and that basically nobody uses except Servo.

**Comment by tomaka** [comment]
That being said, I could still accept it (it's not totally out of scope) even though neither SDL nor GLFW have a similar feature.

But if there was a way to do it without modifying glutin's source code (for example by getting the handle of the window), I'd prefer it.

**Comment by Manishearth** [comment]
Hmm, right. I'm not saying we need a full blown pluggable API here though -- just a restructuring of the relevant code so that what @zmike wants to do can be done externally. Could be as simple as making fields public or something. There might already be a way of doing it without tweaking glutin for all I know :)

**Comment by zmike** [comment]
There is no way to restructure code outside of glutin to provide this exact functionality. The act of creating a window in X11 sets a parent for the new window; glutin already does this internally, and this PR just allows that value to be configurable.

The alternative is to reparent the window outside of glutin, but, in addition to being functionally different due to xserver timings, this can also create issues due to various attribute mismatches of the windows.

**Comment by zmike** [comment]
@glennw also

**Comment by larsbergstrom** [comment]
So, it sounds like we should just land this in the Servo fork of glutin and accept that we might not be able to upstream it? IIRC, we already have Servo-specific changes.

**Comment by Manishearth** [comment]
Sure!

I want to avoid diverging from upstream crates until we absolutely have to; that's all  -- it seems like that is the case here anyway :smile:

**Pull request merged**
