### PR TITLE
Fix broken `link` in dlopen

### PR DESCRIPTION
**Pull request by varkor**
This blocks https://github.com/rust-lang/rust/pull/57139.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/glutin/148)

### CODE REVIEW

**Comment by Eijebong** [comment]
This repository hasn't been used in a while. Servo unforked glutin a few months ago. Maybe this should be marked as archived ?

**Comment by varkor** [comment]
Oh, that's interesting. It's [definitely `servo-glutin`](https://api.travis-ci.org/v3/job/473226865/log.txt) that's causing the problem in https://github.com/rust-lang/rust/pull/57139, so there are presumably other dependencies out of date there that need to be fixed.

> Maybe this should be marked as archived ?

That would probably be less confusing — maybe the servo-glutin crate description could be updated to make note of this on crates.io too.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/57139 is failing in `src/tools/cargotest`, which runs `cargo test` on a few repositories including an old commit of WebRender. Try changing to a newer commit in https://github.com/rust-lang/rust/blob/35a64f8bbfab3e063754cc9fc51a6ad795269b50/src/tools/cargotest/main.rs#L62 ?

**Comment by SimonSapin** [comment]
Well, upstream glutin also uses `#[link="dl"]` https://github.com/tomaka/glutin/blob/2bee4b003d9f2f740e1c139d440ebe15f57c51af/src/api/dlopen.rs#L9

**Comment by varkor** [comment]
@SimonSapin: I've just [made a PR](https://github.com/tomaka/glutin/pull/1093) to fix upstream glutin and once that's done I'll update the dependency in webrender and then the test. Thanks!

**Pull request closed without merging**
