### PR TITLE
Depend on specific versions. Explicitly show an EGL dependency.

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @glennw 

Need to both:
1) Use better strict versions to avoid https://github.com/rust-lang/cargo/issues/2041
2) Actually depend on EGL, which we're generating bindings for

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/49)

### CODE REVIEW

**Comment by glennw** [comment]
Should this also bump the crate version number so it can be published?

**Comment by glennw** [comment]
@larsbergstrom This looks fine to me but travis failed.

**Comment by tomaka** [comment]
You should use gl_generator 0.1.0.
It has exactly the same API and behavior as gl_generator 0.0.28, but it fixes the compilation error that travis sees.

**Comment by metajack** [comment]
pinging @larsbergstrom

**Pull request closed without merging**
