### PR TITLE
Porting to raspberry pi2.

### PR DESCRIPTION
**Pull request by Adenilson**
Please consider merging this as it was required to compile servo on raspberry pi2.

[Review on Reviewable](https://reviewable.io/reviews/servo/glutin/33)

### CODE REVIEW

**Comment by pcwalton** [comment]
Maybe this should go upstream?

**Comment by Adenilson** [comment]
I see that servo uses a forked glutin. Upstream glutin already has some ARM related changes, I've not tested if master would compile.

What are the plans concerning merging this fork with upstream glutin?

**Comment by metajack** [comment]
cc @glennw @tomaka @zmike

These three people would no more about resolving the fork situation.

**Comment by zmike** [comment]
Talked with @Adenilson about it, I think he has a better grasp of the situation now.

Agree with @pcwalton that it's worth submitting upstream if they don't have it yet.

**Comment by tomaka** [comment]
There are only two "controversial" change in servo's fork that I don't really want upstream: the `with_parent` creation parameter, and the fact that it uses a `std::sync::Weak` pointer somewhere instead of an `Arc` (the `Weak` is more correct but is also unstable).

**Comment by Adenilson** [comment]
I tested upstream and it compiles fine in raspberry pi2. 

That being said, if anyone checks out servo today (and the forked glutin), it will require this patch to get things to compile.

**Comment by glennw** [comment]
When I get some time (probably after June) I intend to "resolve" the current issues by:
- Updating servo to use the latest version of glutin.
- Rebasing our two patches on top.
- Investigate if there's some alternate ways to achieve our patches.
- Make it easy to keep up with upstream and apply our local patches if required.

So yes, I would get this change upstream if possible, thanks.

**Comment by tomaka** [comment]
This change is not needed upstream as it has already been fixed.

**Comment by Adenilson** [comment]
Yeah, just like I commented earlier: "... upstream and it compiles fine".

**Comment by metajack** [comment]
Is this still needed? Or did we get this in the last glutin pull?

cc @Adenilson @glennw

**Comment by Adenilson** [comment]
Recent checkout seems to have ARM compile target in Cargo.toml file. I can't test it now, but my guess is that is no longer necessary.

**Pull request closed without merging**
