### PR TITLE
Fixes initial display positioning of viewport on retina screens.

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by SimonSapin** [comment]
Should this (and other changes made in the repo) have gone upstream?

**Comment by glennw** [comment]
I have upstreamed all our changes (that I know of). We should be able to just use the upstream version of glutin for the rustup in theory.

**Comment by SimonSapin** [comment]
Oh, indeed. I was confused by the upstreaming being in different commits.

**Pull request merged**
